# Generated by Django 6.1 on 2026-08-17 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexing_status',
            field=models.CharField(choices=[('never', 'Never indexed'), ('queued', 'Queued'), ('processing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='never', max_length=16),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['indexing_status'], name='knowledge_k_indexin_567b9c_idx'),
        ),
    ]
